{
    "timestamp": "2023-09-16 22:17:28.215616727",
    "level": "WARN",
    "fields": {
        "message": "Removing an unhealthy container",
        "tid": "CtrMrgUnhealthyRemoved",
        "container_id": "cnn_image_classification_gpu.GPU.0-0-44042EAF-D291-FDF4-95F2-D25A7F3C3080",
        "stdout": "",
        "stderr": "[2023-09-17 02:17:27 +0000] [1] [INFO] Starting gunicorn 21.2.0\n[2023-09-17 02:17:27 +0000] [1] [INFO] Listening at: http://0.0.0.0:45773 (1)\n[2023-09-17 02:17:27 +0000] [1] [INFO] Using worker: sync\n[2023-09-17 02:17:27 +0000] [20] [INFO] Booting worker with pid: 20\n[2023-09-17 02:17:27 +0000] [20] [ERROR] Exception in worker process\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py\", line 609, in spawn_worker\n    worker.init_process()\n  File \"/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py\", line 134, in init_process\n    self.load_wsgi()\n  File \"/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py\", line 146, in load_wsgi\n    self.wsgi = self.app.wsgi()\n  File \"/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py\", line 67, in wsgi\n    self.callable = self.load()\n  File \"/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py\", line 58, in load\n    return self.load_wsgiapp()\n  File \"/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py\", line 48, in load_wsgiapp\n    return util.import_app(self.app_uri)\n  File \"/usr/local/lib/python3.8/dist-packages/gunicorn/util.py\", line 371, in import_app\n    mod = importlib.import_module(module)\n  File \"/usr/lib/python3.8/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 848, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/app/server.py\", line 2, in <module>\n    from flask import Flask, request, jsonify\nModuleNotFoundError: No module named 'flask'\n[2023-09-17 02:17:27 +0000] [20] [INFO] Worker exiting (pid: 20)\n[2023-09-17 02:17:27 +0000] [1] [ERROR] Worker (pid:20) exited with code 3\n[2023-09-17 02:17:27 +0000] [1] [ERROR] Shutting down: Master\n[2023-09-17 02:17:27 +0000] [1] [ERROR] Reason: Worker failed to boot.\n"
    },
    "target": "iluvatar_worker_library::services::containers::containermanager"
}
